// <auto-generated />
namespace CartPhill.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class tellsMeTheContextHasChanged : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(tellsMeTheContextHasChanged));
        
        string IMigrationMetadata.Id
        {
            get { return "201503100851374_tellsMeTheContextHasChanged"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
